import java.util.Random;

class Shared {
    int num;
    boolean available = false;
}

class Producer extends Thread {
    Shared s;
    Producer(Shared s) { this.s = s; }
    public void run() {
        Random r = new Random();
        for (int i = 0; i < 10; i++) {
            synchronized (s) {
                while (s.available) {
                    try { s.wait(); } catch (InterruptedException e) {}
                }
                s.num = r.nextInt(100) + 1;
                System.out.println("Number generated by Producer: " + s.num);
                s.available = true;
                s.notify();
            }
        }
    }
}

class Consumer extends Thread {
    Shared s;
    int evenCount = 0;
    Consumer(Shared s) { this.s = s; }
    public void run() {
        for (int i = 0; i < 10; i++) {
            synchronized (s) {
                while (!s.available) {
                    try { s.wait(); } catch (InterruptedException e) {}
                }
                if (s.num % 2 == 0)
                    evenCount++;
                s.available = false;
                s.notify();
            }
        }
        System.out.println("Number of even numbers received by Consumer: " + evenCount);
    }
}

public class q12 {
    public static void main(String[] args) {
        Shared s = new Shared();
        Producer p = new Producer(s);
        Consumer c = new Consumer(s);
        p.start();
        c.start();
        try {
            p.join();
            c.join();
        } catch (InterruptedException e) {}
    }
}
